language: generic
sudo: required
services: 
 - docker

before_instal:
 - docker build -f Dockerfile.dev -t guilevi/docker-react .

script:
 - docker run -e CI=true guilevi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-418240963901"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key: $AWS_SECRET_KEY